image: java:8

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script: 
    - ./gradlew -Dorg.gradle.daemon=false build
  artifacts:
    paths:
      - build/libs/
