name: Release

on:
  push:
    branches:
      - 'release'

jobs:

  build-and-release:
    runs-on: ubuntu-latest
    name: Build and Release
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Test with Gradle
        run: ./gradlew test
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.jar"
          token: ${{ secrets.GITHUB_TOKEN }}