name: Release

on:
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: "build/libs/*.jar"


  release:
    runs-on: ubuntu-latest
    needs: build
    name: Release
    steps:
      - uses: actions/checkout@v2
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.jar"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
